
# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

cloud_cost_monitoring:
  target: "{{ env_var('DBT_PROFILE_TARGET') }}"


    test:
      type: snowflake
      account: hashmap

      user:      "{{ env_var('DBT_PROFILE_TEST_USER') }}"
      password:  "{{ env_var('DBT_PROFILE_TEST_PASSWORD') }}"
      role:      "{{ env_var('DBT_PROFILE_TEST_ROLE') }}"
      database:  "{{ env_var('DBT_PROFILE_TEST_DB') }}"
      warehouse: "{{ env_var('DBT_PROFILE_TEST_WH') }}"
      schema:    "{{ env_var('DBT_PROFILE_TEST_SCHEMA') }}"

      threads: 8
      client_session_keep_alive: False



    prod:
      type: snowflake
      account: hashmap

      user:      "{{ env_var('DBT_PROFILE_PROD_USER') }}"
      password:  "{{ env_var('DBT_PROFILE_PROD_PASSWORD') }}"
      role:      "{{ env_var('DBT_PROFILE_PROD_ROLE') }}"
      database:  "{{ env_var('DBT_PROFILE_PROD_DB') }}"
      warehouse: "{{ env_var('DBT_PROFILE_PROD_WH') }}"
      schema:    "{{ env_var('DBT_PROFILE_PROD_SCHEMA') }}"

      threads: 8
      client_session_keep_alive: False